import type { Property, BlogPost, Testimonial } from "./types";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "פנטהאוז יוקרה עם נוף פנורמי",
    price: 8500000,
    type: "sale",
    bedrooms: 4,
    bathrooms: 3,
    size_sqm: 220,
    floor: 18,
    address: "רחוב הרצל 12",
    neighborhood: "מרכז העיר",
    city: "רמת השרון",
    description:
      "פנטהאוז מדהים בבניין יוקרה חדש. נוף פנורמי לים ולעיר, גימור עילי, מרפסת ענקית.",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    status: "available",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "דירת גן מעוצבת 5 חדרים",
    price: 4900000,
    type: "sale",
    bedrooms: 5,
    bathrooms: 2,
    size_sqm: 165,
    floor: 0,
    address: "שדרות ויצמן 34",
    neighborhood: "גני עמי",
    city: "רמת השרון",
    description:
      "דירת גן נדירה בשכונת היוקרה. גינה פרטית 80 מ״ר, שיפוץ ברמה גבוהה, שקט ואיכותי.",
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    status: "available",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "דירת 4 חדרים בפרויקט חדש",
    price: 22000,
    type: "rent",
    bedrooms: 4,
    bathrooms: 2,
    size_sqm: 130,
    floor: 5,
    address: "רחוב סוקולוב 8",
    neighborhood: "מרכז",
    city: "רמת השרון",
    description:
      "דירה בפרויקט יוקרה חדש, מעלית, חניה כפולה, מחסן. זמינה מיידית.",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    status: "available",
    featured: true,
    created_at: new Date().toISOString(),
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Noy Carmel",
    rating: 5,
    text: "עידן מקצועי ברמות הכי גבוהות. נעים לעבוד איתו והוא עושה מעל ומעבר כדי להשיג את התוצאות הכי טובות. מומלץ בחום.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Orit Ronell",
    rating: 5,
    text: "אחלה עידן, מתווך שאני סומכת עליו. אמין, שירותי, מבין את הצרכים והפוטנציאל ולא לוחץ עליך לרדת במחיר סתם או משחק משחק כפול. ממליצה ממש.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Meirav Vizer",
    rating: 5,
    text: "עידן יסודי, מסביר פנים, יש לו המון סבלנות ומנסה למצוא את הנכס בדיוק שיתאים לנו — היה לנו מאוד נעים לעבוד איתו.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "אדיר שעשוע",
    rating: 5,
    text: "עידן אלוף אין עליו בעולם! כל מי שלוקח אותו יזכה. דאג לנו למחיר פצצה ולמכירה מהירה. אלוף עולם.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "shay gurvitz",
    rating: 5,
    text: "עידן פשוט מקצוען ברמה, קשוב לצרכים של הלקוח, נותן תחושת ביטחון, והכי חשוב — שנתן את כל הלב והנשמה ומסור ללא דופי.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "שובל אביטן",
    rating: 5,
    text: "עידן והצוות שלו מקצועיים לאורך כל הדרך, השירות היה אישי ועד שלא מצאנו בול את מה שחיפשנו — הם לא עזבו אותנו לרגע. אין עליהם!",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Efrat Z. Fink",
    rating: 5,
    text: "עידן עבד במקצועיות רבה, באווירה טובה ומכבדת, ותוך זמן קצר הגיע לתוצאות. מומלץ מאד!",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "טל היינברג",
    rating: 5,
    text: "מקצוען אמיתי! מכר לי את הנכס מהר מהצפוי והכל בסובלנות בשילוב מקצועיות שיא ובחיוך גדול.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "MOSHE zagrizak",
    rating: 5,
    text: "מקצוען אמיתי. עידן עזר לי לאפיין בצורה מדהימה את ההשקעה שמתאימה לי. ליווה אותי במיקוד, איתור, מציאת העסקה, עזרה במו\"מ ואפילו בתנאי ההסכם. וכמובן בן אדם טוב — שזה לא פחות חשוב בתחום הזה.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "משה בן דוד",
    rating: 5,
    text: "מדובר באדם ישר, מקצועי, אדיב, מסביר פנים ואחד שלוקח כל עסקה ברצינות כאילו הנכס שלו. אין ספק שאנחנו ממליצים עליו.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Amit Dahan",
    rating: 4,
    text: "עידן מלך, דחף את העסקה קדימה כמו שצריך ודאג לאינטרסים של שני הצדדים. תודה רבה.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "דנה קפו-אייזנברג",
    rating: 4,
    text: "מקצועי-ענייני-אנושי. תענוג לעבוד עם עידן — כל מה שצריך מבעל מקצוע.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    name: "ליאור ממו",
    rating: 5,
    text: "עידן מקצועי ונעים, איש עבודה אמיתי. כיף לעבוד עם מתווך שבאמת נותן ערך.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Amit Lavi",
    rating: 5,
    text: "שירות וליווי חברי ומקצועי! תודה על הכל.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "5 טעויות שכל רוכש דירה בפעם הראשונה עושה",
    slug: "5-mistakes-first-time-buyers",
    excerpt:
      "רכישת דירה ראשונה היא אחד הצעדים הגדולים בחיים. הנה הטעויות הנפוצות ביותר — ואיך להימנע מהן.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    keywords: ["רכישת דירה", "דירה ראשונה", "נדל״ן", "טיפים"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "למה רמת השרון היא שוק הנדל״ן החם של 2025",
    slug: "ramat-hasharon-real-estate-2025",
    excerpt:
      "מחירים, מגמות, ופרויקטים חדשים. סקירה מקיפה על שוק הנדל״ן ברמת השרון ומה צפוי בשנה הקרובה.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    keywords: ["רמת השרון", "נדל״ן 2025", "מחירי דירות", "שוק הנדל״ן"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "מחשבון משכנתא: כמה בית אתם יכולים להרשות לעצמכם?",
    slug: "mortgage-calculator-guide",
    excerpt:
      "המדריך המלא לתכנון משכנתא: הון עצמי נדרש, ריביות, פריסה — והכלים שיעזרו לכם לקבל החלטה נכונה.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    keywords: ["משכנתא", "מימון נדל״ן", "הלוואת משכנתא", "ריבית"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
