import type { Property, BlogPost, Testimonial } from "./types";

export const mockProperties: Property[] = [
  {
    id: "babi-hanesim-6",
    title: "3.5 חדרים בבבלי – פנינה עם תחושת קיבוץ בעיר",
    price: 3890000,
    type: "sale",
    bedrooms: 3.5,
    bathrooms: 1,
    size_sqm: 80,
    floor: 2,
    address: "הנשיאים 6",
    neighborhood: "בבלי",
    city: "תל אביב",
    description:
      "למכירה בבבלי המבוקשת – דירת 3.5 חדרים שהיא פנינה אמיתית עם תחושה של קיבוץ בעיר ובמרחק הליכה מפארק הירקון. רחוב שקט וחד-סטרי, קומה 2 עם מעלית. חלל אירוח מרווח ומואר להפליא, מרפסת שמש 6 מ״ר, חניה פרטית ומקלט מסודר בבניין. פוטנציאל השבחה אדיר בזכות קרבה לתחנות הרכבת הקלה והמטרו העתידיים. הזדמנות מיוחדת למשפחות או משקיעים שמחפשים נכס מבוקש באזור עם איכות חיים נדירה.",
    images: [
      "/properties/babi-1.jpg",
    ],
    status: "available",
    featured: true,
    created_at: new Date().toISOString(),
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Noy Carmel",
    rating: 5,
    text: "עידן מקצועי ברמות הכי גבוהות. נעים לעבוד איתו והוא עושה מעל ומעבר כדי להשיג את התוצאות הכי טובות. מומלץ בחום.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Orit Ronell",
    rating: 5,
    text: "אחלה עידן, מתווך שאני סומכת עליו. אמין, שירותי, מבין את הצרכים והפוטנציאל ולא לוחץ עליך לרדת במחיר סתם או משחק משחק כפול. ממליצה ממש.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Meirav Vizer",
    rating: 5,
    text: "עידן יסודי, מסביר פנים, יש לו המון סבלנות ומנסה למצוא את הנכס בדיוק שיתאים לנו — היה לנו מאוד נעים לעבוד איתו.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "אדיר שעשוע",
    rating: 5,
    text: "עידן אלוף אין עליו בעולם! כל מי שלוקח אותו יזכה. דאג לנו למחיר פצצה ולמכירה מהירה. אלוף עולם.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "shay gurvitz",
    rating: 5,
    text: "עידן פשוט מקצוען ברמה, קשוב לצרכים של הלקוח, נותן תחושת ביטחון, והכי חשוב — שנתן את כל הלב והנשמה ומסור ללא דופי.",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "שובל אביטן",
    rating: 5,
    text: "עידן והצוות שלו מקצועיים לאורך כל הדרך, השירות היה אישי ועד שלא מצאנו בול את מה שחיפשנו — הם לא עזבו אותנו לרגע. אין עליהם!",
    source: "google",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Efrat Z. Fink",
    rating: 5,
    text: "עידן עבד במקצועיות רבה, באווירה טובה ומכבדת, ותוך זמן קצר הגיע לתוצאות. מומלץ מאד!",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "טל היינברג",
    rating: 5,
    text: "מקצוען אמיתי! מכר לי את הנכס מהר מהצפוי והכל בסובלנות בשילוב מקצועיות שיא ובחיוך גדול.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "MOSHE zagrizak",
    rating: 5,
    text: "מקצוען אמיתי. עידן עזר לי לאפיין בצורה מדהימה את ההשקעה שמתאימה לי. ליווה אותי במיקוד, איתור, מציאת העסקה, עזרה במו\"מ ואפילו בתנאי ההסכם. וכמובן בן אדם טוב — שזה לא פחות חשוב בתחום הזה.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "משה בן דוד",
    rating: 5,
    text: "מדובר באדם ישר, מקצועי, אדיב, מסביר פנים ואחד שלוקח כל עסקה ברצינות כאילו הנכס שלו. אין ספק שאנחנו ממליצים עליו.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Amit Dahan",
    rating: 4,
    text: "עידן מלך, דחף את העסקה קדימה כמו שצריך ודאג לאינטרסים של שני הצדדים. תודה רבה.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "דנה קפו-אייזנברג",
    rating: 4,
    text: "מקצועי-ענייני-אנושי. תענוג לעבוד עם עידן — כל מה שצריך מבעל מקצוע.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    name: "ליאור ממו",
    rating: 5,
    text: "עידן מקצועי ונעים, איש עבודה אמיתי. כיף לעבוד עם מתווך שבאמת נותן ערך.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Amit Lavi",
    rating: 5,
    text: "שירות וליווי חברי ומקצועי! תודה על הכל.",
    source: "google",
    featured: false,
    created_at: new Date().toISOString(),
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "5 טעויות שכל רוכש דירה בפעם הראשונה עושה",
    slug: "5-mistakes-first-time-buyers",
    excerpt:
      "רכישת דירה ראשונה היא אחד הצעדים הגדולים בחיים. הנה הטעויות הנפוצות ביותר — ואיך להימנע מהן.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    keywords: ["רכישת דירה", "דירה ראשונה", "נדל״ן", "טיפים"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "למה רמת השרון היא שוק הנדל״ן החם של 2025",
    slug: "ramat-hasharon-real-estate-2025",
    excerpt:
      "מחירים, מגמות, ופרויקטים חדשים. סקירה מקיפה על שוק הנדל״ן ברמת השרון ומה צפוי בשנה הקרובה.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    keywords: ["רמת השרון", "נדל״ן 2025", "מחירי דירות", "שוק הנדל״ן"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "מחשבון משכנתא: כמה בית אתם יכולים להרשות לעצמכם?",
    slug: "mortgage-calculator-guide",
    excerpt:
      "המדריך המלא לתכנון משכנתא: הון עצמי נדרש, ריביות, פריסה — והכלים שיעזרו לכם לקבל החלטה נכונה.",
    content: "",
    cover_image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    keywords: ["משכנתא", "מימון נדל״ן", "הלוואת משכנתא", "ריבית"],
    published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
